---
title: "R Notebook"
output: html_notebook
---


```{r, Lab 6, fig.width = 10, fig.height = 5}
library(tidyverse)
library(sqldf)
library(eeptools)
library(Rcpp, "1.0.7")
library(reshape2)
library(lubridate)
# lab 6
df = read.csv("/Users/Grim/Documents/GitHub/Masters-Classes-L-O/Data Visualisation/data/studentresult.csv", sep= ',' , header=T )


# Q1
test_marks = sqldf('select Subject, Name, round(avg(Mark_Written) + avg(Mark_Oral), 1)/2 as Test_mark from df
group by Name, Subject')
plot = ggplot(data = test_marks, aes(Name, Test_mark, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Student Name", y="Grade Average", 
       title="Q1 What are the total marks for each student for each subject?", fill="Subjects")
plot

# Q2
test_marks_2 = sqldf('select DOB, Subject, Name, round(avg(Mark_Written) + avg(Mark_Oral), 1)/2 as Test_mark from df
group by Name, Subject')

test_marks_2$DOB = year(strptime("11-11-2021", format = "%d-%m-%Y")) - year(strptime(test_marks_2$DOB, format = "%d-%m-%Y"))
names(test_marks_2)[1] = "Age"
plot = ggplot(data=test_marks_2, aes(x=Age, y=Test_mark, group=1)) +
  geom_line(color="blue")+
  geom_point() + labs(x="Age", y="Grade Average", 
       title="Q2 What is the relationship between age and mark?", fill="Subjects")

plot

# Q3 
test_marks_3 = sqldf('select Name, avg(Mark_Written) as "Written Exam", avg(Mark_Oral) as "Oral Exam" from df
group by Name')
pivot_data = melt(test_marks_3 ,  id.vars = 'Name', variable.name = 'Exam')
plot = ggplot(data = pivot_data, aes(Name, value, fill=as.factor(Exam))) + geom_col(position = "dodge") + labs(x="Student Name", y="Avg Test Score", title="Q3 Did any students do better on their written compared with their oral?", fill="Subjects")
plot

# Q4
test_marks_4 = sqldf('select Subject, round((avg(Mark_Written) + avg(Mark_Oral))/2) as "Test Score" from df
group by subject')
plot = ggplot(data = test_marks_4, aes(Subject, `Test Score`, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Subject Name", y="Grade Average", title="Q4 What subject obtained the best results on average?", fill="Subjects")
plot

# Q5
test_marks_5 = sqldf('select Subject, Name, Year, round(avg(Mark_Oral)) as "Avg Oral Score" from df group by name, subject, year')


ggplot(data=test_marks_5, aes(x=Name, y=test_marks_5$`Avg Oral Score`, fill=Subject)) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  theme_minimal() +
  facet_wrap(~Year) + 
  labs(x="Subject Name", y="Grade Average", title="Q5 What are the average results in oral exams across all subjects and all years per student?", fill="Subjects")
  # ignore the error message, it prevents data from being properly displayed for avgs


```

```{r, Lab 7, fig.width = 10, fig.height = 6}
library(tidyverse)
library(sqldf)
library(eeptools)
library(Rcpp, "1.0.7")
library(reshape2)
library(lubridate)
library(magrittr)
library(dplyr)

# lab 7
df = read.csv("/Users/Grim/Documents/GitHub/Masters-Classes-L-O/Data Visualisation/data/studentresult.csv", sep= ',' , header=T )
test_marks = sqldf('select Name, avg(Mark_Written) as "Written Exam", avg(Mark_Oral) as "Oral Exam" from df
group by Name')
pivot_data = melt(test_marks ,  id.vars = 'Name', variable.name = 'Exam')
plot = ggplot(data = pivot_data, aes(Name, value, fill=as.factor(Exam))) + geom_col(position = "dodge") + labs(x="Student Name", y="Avg Test Score", title="Q1 plot the results for the written and oral exams in two bars per student", fill="Subjects")


# Q2-1
# Plot one variable counting the instances that fall in each bin (Histogram). Bin size can be adjusted with the command binwidth.
test_marks = sqldf('select Subject, Name, round(Mark_Written) as "Mark Written" from df
group by Name, Subject')

hist(test_marks$`Mark Written`, 
     col="skyblue2", 
     xlab="Mark Ranges for Students",
     ylab="Score Frequency",
     main="Q2-1")


# Q2-2
# Change the orientation of a bar chart to be horizontal rather than vertical. (1 mark)
qplot(test_marks$`Mark Written`, geom="histogram", xlab="Mark Ranges for Students", ylab="Score Frequency") + coord_flip()


# Q2-3
# Fit a line to a scatter plot of age against Written Marks. 
test_marks_age = sqldf('select DOB, Subject, Name, Mark_Written as "Mark Written" from df
group by Name, Subject')

test_marks_age$DOB = year(strptime("11-11-2021", format = "%d-%m-%Y")) - year(strptime(test_marks_age$DOB, format = "%d-%m-%Y"))
names(test_marks_age)[1] = "Age"

plot = ggplot(data=test_marks_age, aes(x=Age, y=test_marks_age$`Mark Written`, group=1)) +
  geom_line(color="skyblue3")+
  geom_point() + labs(x="Age", y="Written Marks", 
                      title="Q2-3 Fit a line to a scatter plot of age against Written Marks", fill="Subjects")
plot

# Q2-4
# Create a scatter plot with a separate line for each data series (per subject). (1 mark)

test_marks_age = sqldf('select DOB, Subject, Name, Mark_Written as "Mark Written" from df
group by Name, Subject')

test_marks_age$DOB = year(strptime("11-11-2021", format = "%d-%m-%Y")) - year(strptime(test_marks_age$DOB, format = "%d-%m-%Y"))
names(test_marks_age)[1] = "Age"

plot = ggplot(data=test_marks_age, aes(x=Age, y=test_marks_age$`Mark Written`, group=Subject, colour=Subject)) +
  geom_line()+
  geom_point() + labs(x="Age", y="Written Marks", 
                      title="Q2-4 Create a scatter plot with a separate line for each data series", fill="Subjects")

plot

# Q2-5
# Create a bubble chart using ggplot by creating a scatter plot 
# and adding the third dimension in the aesthetic option size. A fourth dimension can be added using the colour fill
test_marks_5 = sqldf('select DOB, Subject, Name, Mark_Written as "Mark Written" from df
group by Name, Subject')

#plot = ggplot(test_marks_5, aes(x=Subject, y=test_marks_5$`Mark Written`)) + geom_point(aes(size=test_marks_5$`Mark Written`))
#plot

test_marks_5 %>%
  arrange(desc(test_marks_5$`Mark Written`)) %>%
  #mutate(country = factor(country, country)) %>%
  ggplot(aes(x=Subject, y=test_marks_5$`Mark Written`, size=test_marks_5$`Mark Written`, color=test_marks_5$`Mark Written`)) +
  geom_point(alpha=0.5) +
  scale_size(range = c(.1, 24), name="Written Exam Marks") + labs(title = "Q2-5", x = "Subjects", y = "Written Marks", color = "Written Exam Marks Concentration")


# https://stackoverflow.com/questions/14860078/plot-multiple-lines-data-series-each-with-unique-color-in-r
# https://r-coder.com/scatter-plot-r/

```

```{r, Lab 8, fig.width = 10, fig.height = 6}
library(tidyverse)
library(sqldf)
library(eeptools)
library(Rcpp, "1.0.7")
library(reshape2)
library(lubridate)
library(magrittr)
library(dplyr)
library(maps)

# lab 8
df = read.csv("/Users/Grim/Documents/GitHub/Masters-Classes-L-O/Data Visualisation/data/OlympicGames.csv", sep= ',' , header=T )

df

# 5. Visualisation Exercises
# Please answer the following questions. Use a visualisation to support the answer for each
# question. Experiment with the different types of charts and options ggplot offers. Please
# place the visualisations underneath each question.

# 1) What country has won most Silver medals since 2000? (2 marks)
# 2) How is the gender balance amongst the United States gold medalist? (2 marks)
# 3) What are the best sports for Sweden, USA, Austria and Switzerland? (2 marks)
# 4) Who has the most total medals? (2 marks)
# 5) What is the variation and spread of ages amongst gold and silver medalists? (2 marks)


mapdata = map_data("world")
mapdata
# 1) What country has won most Silver medals since 2000?
df_year_2000 = with(df, df[(Year >= 2000),])

df_year_2000_tmp = sqldf('select Year, count(Medal) as Medal, Country from df_year_2000 where Medal == "silver" group by Country')
names(df_year_2000_tmp)[3] = "region"
df_year_2000_tmp
silver_medals = right_join(mapdata, df_year_2000_tmp, by="region")
silver_medals

# ====> ToDo add labels for countries

map1 = ggplot(silver_medals, aes( x = silver_medals$long, y = silver_medals$lat, group=group, fill = as.numeric(Medal))) +
  geom_polygon(color = "white") + labs(title="What country has won most Silver medals since 2000?", fill="Silver Medals count won since since year 2000")

map1


map1 = ggplot(silver_medals, aes( x = silver_medals$long, y = silver_medals$lat, group=group)) +
  geom_polygon(aes(fill = Medal), color = "black") + labs(title="What country has won most Silver medals since 2000?", fill="Silver Medals count won since since year 2000")

map1




map2 = map1 + scale_fill_gradient(name = "Total Medals Won", low = "white", high = "blue", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map2


# 2) How is the gender balance amongst the United States gold medalist? - Done
df_usa = with(df, df[(Country == "USA"),])
df_usa = with(df_usa, df_usa[(Medal == "gold"),])

df_usa_tmp = sqldf('select count(Gender) as Medal_Count, Medal, Gender from df_usa where Country="USA" group by Gender')
df_usa_tmp

plot = ggplot(data = df_usa_tmp, aes(Gender, Medal_Count, fill=as.factor(Gender))) +
  geom_col(position="dodge") + 
  labs(x="Genders", y="Medals Won", title="How is the gender balance amongst the United States gold medalist?", fill="Genders")

plot


# 3) What are the best sports for Sweden, USA, Austria and Switzerland? - Done

df_countires_list = with(df, df[(Country == c("USA", "Sweden", "Austria", "Switzerland")),])
df_countires_list_tmp = sqldf('select Event, count(Medal) as Medal_Count, Country from df_countires_list group by Country, Event')

plot = ggplot(data = df_countires_list_tmp, aes(Event, Medal_Count, fill=as.factor(Country))) +
  geom_col(position="dodge") + 
  labs(x="Event Name", y="Medals Won", title="What are the best sports for Sweden, USA, Austria and Switzerland?", fill="Country") + facet_wrap( ~ Country)

plot

print("I tried to filer by gold medals only to try and reduce the amount of columns but thats not enough")
df_countires_list = with(df, df[(Country == c("USA", "Sweden", "Austria", "Switzerland")),])
df_countires_list = with(df_countires_list, df_countires_list[(Medal == "gold"),])


df_countires_list_tmp = sqldf('select Event, count(Medal) as Medal_Count, Country from df_countires_list where Medal_Count != 0 group by Country, Event')


plot = ggplot(data = df_countires_list_tmp, aes(Event, Medal_Count, fill=as.factor(Country))) +
  geom_col(position="dodge") + 
  labs(x="Event Name", y="Medals Won", title="What are the best sports for Sweden, USA, Austria and Switzerland?", fill="Country") + facet_wrap( ~ Country)

plot


# 4) Who has the most total medals? - Done

medals_total = sqldf('select count(Medal) as Medal_Count, Country from df group by Country')
medals_total

plot = ggplot(data = medals_total, aes(Country, Medal_Count, fill=as.factor(Country))) +
  geom_col(position="dodge") + 
  labs(x="Country Name", y="Medals ", title="Who has the most total medals?", fill="Countries")

plot


# 5) What is the variation and spread of ages among gold and silver medalists?
tmp_df = df
tmp_df$DOB = year(strptime("11-11-2021", format = "%d-%m-%Y")) - year(strptime(tmp_df$DOB, format = "%d-%m-%Y"))
names(tmp_df)[1] = "Age"
medal_age = tmp_df %>% drop_na()
medal_age_df = sqldf('select Athlete_Age, Medal from medal_age where Medal != "bronze"')
plot = ggplot(data = medal_age_df, aes(Athlete_Age, Medal, fill=as.factor(Athlete_Age))) + 
  geom_col(position="dodge") + labs(x="Medal Name", y="Athlete Age", 
           title="Q5 What is the variation and spread of ages among gold and silver medalists?", fill="Athlete Age Range") + coord_flip()
plot
# 5)
```



```
test_marks
plot = ggplot(data = test_marks, aes(Name, Test_mark, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Student Name", y="Grade Average", 
       title="What are the total marks for each student for each subject?", fill="Subject Name")
plot


# Q2

test_marks_2 = sqldf('select DOB, Subject, Name, round((avg(Mark_Written) + avg(Mark_Oral))/2) as Test_mark from df
group by Name, Subject')
as.numeric(difftime(as.Date("2021-01-01", format=""), as.Date("2011-01-01"), unit="year"))

t = interval(ymd(Sys.Date(), format='%y/%m/%d'), ymd(test_marks_2$DOB))
time_length(t, "year")


test_marks_2$DOB = 3
test_marks_2


int <- interval(ymd("1900-01-01"), ymd("1999-12-31"))
time_length(int, "year")




test_marks_5_2013 = with(test_marks_5, test_marks_5[(Year == 2013),])
test_marks_5_2014= with(test_marks_5, test_marks_5[(Year == 2014),])
test_marks_5_2015 = with(test_marks_5, test_marks_5[(Year == 2015),])


plot_2013 = ggplot(data = test_marks_5_2013, aes(Name, test_marks_5_2013$`Avg Oral Score`, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Student Name", y="Grade Average", fill="Subject Name")
plot_2014 = ggplot(data = test_marks_5_2014, aes(Name, test_marks_5_2014$`Avg Oral Score`, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Student Name", y="Grade Average", fill="Subject Name")
plot_2015 = ggplot(data = test_marks_5_2015, aes(Name, test_marks_5_2015$`Avg Oral Score`, fill=as.factor(Subject))) + geom_col(position="dodge") + labs(x="Student Name", y="Grade Average", fill="Subject Name")


plots = cbind(plot_2013, plot_2014, plot_2015)


```
