---
title: "Assigment 3 Linear and Logistic Regression Models - C15311966 Maks Drzezdzon"
output: html_notebook
---



```{r - setup, load data (Submission deadline: 1.00pm 14th March 2022) }
library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(psych) # Some useful descriptive functions
library(semTools) #For skewness and kurtosis
library(FSA) # For percentage
library(car) # For Levene's test for homogeneity of variance 
library(effectsize) # To calculate effect size for t-test
library(kableExtra) # Used to generate report ready tables
library(tidyverse) # data wrangling 
library(gtsummary) # generate table for model results 
library(multcomp) # needed for glht 
library(emmeans)
require(ggiraph) # to use ggPredict
require(ggiraphExtra) # to use ggPredict
require(plyr)
library(plotly) # density plot
library(gridExtra)
library(PCAmixdata)


# Different subsets of data for experiments if time allows for it
untouched_dataset = read.csv("telecoms_churn.csv")
full_customer_dataset = subset(untouched_dataset, select = -c(X))
customer_dataset_user_has_internet = full_customer_dataset[which(full_customer_dataset$internetservice != 'No'), ]
customer_dataset_user_has_internet = subset(customer_dataset_user_has_internet, select = -c(internetservice))
customer_dataset_user_no_internet = full_customer_dataset[which(full_customer_dataset$internetservice == 'No'), ]
customer_dataset_user_no_internet = subset(customer_dataset_user_no_internet, select = -c(internetservice))

# $logcells = round(data$logcells, digit=5)


anovatab =
  function(mod){
    tab=as.matrix(anova(mod))
    rows=dim(tab)[1]
    moddf=sum(tab[,1])-tab[rows,1]
    ssmodel=sum(tab[,2])-tab[rows,2]
    msmodel=ssmodel/moddf
    f=msmodel/tab[rows,3]
    p=1-pf(f,moddf,tab[rows,1])
    tab2=tab[(rows-1):rows,]
    tab2[1,1:5]=c(moddf,ssmodel,msmodel,f,p)
    tab2=rbind(tab2,c(moddf+tab2[2,1],ssmodel+tab2[2,2],rep(NA,3)))
    rownames(tab2)=c('Model','Error','Total')
    colnames(tab2)[1]='df'
    return(print(tab2,na.print = "" , quote = FALSE,digits=3))
  }

get_var_name = function(var) {
  # get the literal name of the variable 
  deparse(substitute(var))
}


get_plots = function(df, df_name, columns_to_assess, target){
  # @df => what df will be plotted 
  # @df_name => name of df
  # @columns_to_assess = which cols do you want to graph
  # @target = your y value
  
  for (col in columns_to_assess){
      bar_plot = ggplot(df, aes_string(x=col,
                                  y=target, 
                                  show.legend = T)) + 
                  geom_bar(stat="identity") + 
                  ggtitle(paste0("Effect of ", aes_string(x=col), " on customer churn for ", df_name)) + 
                  theme(plot.title = element_text(hjust = 0.5))
      print(bar_plot)
      
  }
  
  
  # https://stats.stackexchange.com/questions/351781/how-to-plot-binary-presence-absence-1-0-data-against-continuous-variables
  conditional_density_plot = ggplot(df, aes(x=monthlycharges, fill=factor(churn))) + 
           geom_density(position = "stack") + 
           xlab("monthlycharges") + labs(fill='churn') +
           ggtitle(paste0("Effect of ~monthlycharges on customer churn for ", df_name)) + 
           theme(legend.text=element_text(size=12), 
                 axis.title=element_text(size=14),
                 plot.title = element_text(size=11))

  
  return(conditional_density_plot)
  
  
}


combine_dfs_freq_table = function(columns, df){
  # hard coded data set full_customer_dataset
  # @columns => what columns will be present in the frequency table  
  df_list = list()
  i=1
  for (col in cols){
    tmp_df = data.frame(round(prop.table(table(df[[col]])) * 100, 2))
    colnames(tmp_df)[1] = "Values"
    tmp_df['Column Name'] = col
    df_list[[i]] = tmp_df
    i=i+1
  }
  final_df = do.call(rbind, df_list)
  colnames(final_df)[2] = "% Representation of Column"
  final_df = final_df %>% relocate('Column Name', .before = "Values")
  return(final_df)
}


```



```{r - 1) Get Descriptive Statistics (Submission deadline: 1.00pm 14th March 2022)}
"
Using an R programme read these data into a data.frame and obtain basic descriptive
statistics/plots of the data. Present salient features from this exploratory data analysis
in your report.
"

# https://www2.nau.edu/lrm22/lessons/graph_tips/graph_tips.html#:~:text=The%20independent%20variable%20belongs%20on,%2Daxis%20(vertical%20line).


has_0 = full_customer_dataset[which(full_customer_dataset$churn == '0'), ]
has_1 = full_customer_dataset[which(full_customer_dataset$churn == '1'), ]

cols_list = colnames(full_customer_dataset)
cols = cols_list[cols_list != "churn" & cols_list != "customerid" & cols_list != "monthlycharges"]

get_plots(full_customer_dataset, get_var_name(full_customer_dataset), cols, "churn")
get_plots(customer_dataset_user_has_internet, get_var_name(customer_dataset_user_has_internet), cols, "churn")
get_plots(customer_dataset_user_no_internet, get_var_name(customer_dataset_user_no_internet), cols, "churn")




```


```{r - generate CI and df tables for temp}

df = full_customer_dataset
kbl(df) %>%
 kable_classic(full_width = F)

cols_list = colnames(df)
cols = cols_list[cols_list != "customerid" & cols_list != "monthlycharges"]
df = subset(df, select=c(cols))
data=df
table_df = combine_dfs_freq_table(cols, df)
kbl(table_df) %>%
 kable_classic(full_width = F)

df = customer_dataset_user_has_internet
cols_list = colnames(df)
cols = cols_list[cols_list != "customerid" & cols_list != "monthlycharges"]
df = subset(df, select=c(cols))
table_df = combine_dfs_freq_table(cols, df)
kbl(table_df) %>%
 kable_classic(full_width = F)

df = customer_dataset_user_no_internet
cols_list = colnames(df)
cols = cols_list[cols_list != "customerid" & cols_list != "monthlycharges"]
df = subset(df, select=c(cols))
table_df = combine_dfs_freq_table(cols, df)
kbl(table_df) %>%
 kable_classic(full_width = F)

```


```{r - 2) create models (Submission deadline: 1.00pm 14th March 2022)}

# (.)^2 maps an interaction between all variables such as x1:x2 + x1:x3 + x2:x3... etc etc 
df = customer_dataset_user_no_internet
df = customer_dataset_user_has_internet



df = full_customer_dataset
cols_list = colnames(df)
cols = cols_list[cols_list != "customerid"]
data = subset(df, select=c(cols))

glm1 = glm(churn ~ (.)^2, data = data)

# plot(glm1)
anova(glm1, test='F')
drop1(glm1, test='F')
summary(glm1)
vcov(glm1)
confint(glm1)

emmeans(glm1, ~monthlycharges+partner+paymentmethod)
lsmeans(glm1, ~paymentmethod:partner, adjust="fdr")

# interaction plot
emmip(glm1, paymentmethod~partner+internetservice) + theme(axis.text=element_text(size=7),
        axis.title=element_text(size=16, face="bold"))


glm1 %>% tbl_regression()
# https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html


```


```{r - 3) Write report (Submission deadline: 1.00pm 14th March 2022)}
# https://stackoverflow.com/questions/14423325/confidence-intervals-for-predictions-from-logistic-regression
new_data = data.frame(gender="Male", partner="Yes", monthlycharges=70.0, internetservice="Fiber optic", paymentmethod="Electronic check")
preds = predict(glm1, new_data, interval = "confidence")
preds
preds = predict(glm1, new_data, se.fit = TRUE, type="response")
critval = qnorm(0.975) ##  95% CI
upr = preds$fit + (critval * preds$se.fit)
lwr = preds$fit - (critval * preds$se.fit)
fit = preds$fit
conf_inter = data.frame(upper_ci=round(upr,2), lower_ci=round(lwr,2), prediciton_probability=round(fit,2))

kbl(conf_inter) %>%
 kable_classic(full_width = F)



# use more plots?
scatter_plot = ggplot(df, aes(x=monthlycharges,
                                y=churn, 
                                show.legend = T)) + 
                geom_point(size=2) + 
                ggtitle("Effect of temperature/additive on carbon fibre strength") + 
                theme(plot.title = element_text(hjust = 0.5))
scatter_plot

# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/anova/how-to/one-way-anova/interpret-the-results/key-results/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/multiple-regression/before-you-start/overview/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/simple-regression/before-you-start/overview/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/covariance/overview/


```