---
title: "Assigment 1 Linear and Logistic Regression Models - C15311966 Maks Drzezdzon"
output: html_notebook
---



```{r - setup, load data (Submission deadline: 1.00pm 14th March 2022) }
library(pastecs) #For creating descriptive statistic summaries
library(ggplot2) #For creating histograms with more detail than plot
library(psych) # Some useful descriptive functions
library(semTools) #For skewness and kurtosis
library(FSA) # For percentage
library(car) # For Levene's test for homogeneity of variance 
library(effectsize) # To calculate effect size for t-test
library(kableExtra) # Used to generate report ready tables
library(tidyverse) # data wrangling 
library(gtsummary) # generate table for model results 
library(multcomp) # needed for glht 
library(emmeans)
require(ggiraph) # to use ggPredict
require(ggiraphExtra) # to use ggPredict
require(plyr)

data = read.csv("carbon_fibre.csv")
data = subset(data, select = -c(X))

# $logcells = round(data$logcells, digit=5)


anovatab <-
  function(mod){
    tab=as.matrix(anova(mod))
    rows=dim(tab)[1]
    moddf=sum(tab[,1])-tab[rows,1]
    ssmodel=sum(tab[,2])-tab[rows,2]
    msmodel=ssmodel/moddf
    f=msmodel/tab[rows,3]
    p=1-pf(f,moddf,tab[rows,1])
    tab2=tab[(rows-1):rows,]
    tab2[1,1:5]=c(moddf,ssmodel,msmodel,f,p)
    tab2=rbind(tab2,c(moddf+tab2[2,1],ssmodel+tab2[2,2],rep(NA,3)))
    rownames(tab2)=c('Model','Error','Total')
    colnames(tab2)[1]='df'
    return(print(tab2,na.print = "" , quote = FALSE,digits=3))
  }


```



```{r - 1) Get Descriptive Statistics (Submission deadline: 1.00pm 14th March 2022)}
"
Using an R programme read these data into a data.frame and obtain basic descriptive
statistics/plots of the data. Present salient features from this exploratory data analysis
in your report.
"

# https://www2.nau.edu/lrm22/lessons/graph_tips/graph_tips.html#:~:text=The%20independent%20variable%20belongs%20on,%2Daxis%20(vertical%20line).



tmp_df = data # store reference
data$additive = as.factor(data$additive)
data$temperature = as.factor(data$temperature)


# TODO plot both for y
# use more plots?
scatter_plot = ggplot(data, aes(x=temperature,
                                y=strength, 
                                show.legend = T, color=additive)) + 
                geom_point(size=2) + 
                ggtitle("Effect of temperature/additive on carbon fibre strength") + 
                stat_smooth(method = "lm", formula = y ~ x, size = 1) + 
                theme(plot.title = element_text(hjust = 0.5))

  

scatter_plot




# reset reference 
data = tmp_df


```


```{r - generate CI and df tables for temp}
kbl(data) %>%
 kable_classic(full_width = F)

group_means=by(data$strength, data$temperature, t.test)

group_means=matrix(c(unlist(group_means[['High']][5:4]),
                     unlist(group_means[['Low']][5:4])),
                     nrow=2, ncol=3, byrow=T)

group_means
group_means = data.frame(cbind(group_means, c("High", "Low")))

# convert to int

group_means$X1 = round(as.integer(group_means$X1), digit=2)
group_means$X2 = round(as.integer(group_means$X2), digit=2)
group_means$X3 = round(as.integer(group_means$X3), digit=2)

colnames(group_means)=c('Mean','Lower CI 95%','Upper CI 95%','Temperature')

group_means

ggplot(group_means, aes(x=Temperature, y=group_means[,1])) +
  geom_errorbar(aes(ymin=`Lower CI 95%`, ymax=`Upper CI 95%`), width=.1) +
  geom_line() + 
  geom_point() + 
  expand_limits(y=c(5, 20)) + 
  ylab("Carbon Fibire Strength") +
  xlab('Temperature') + 
  labs(title="Average Carbon Fibire Strength at Temperature & 95% CIs") + 
  theme(text = element_text(size=13), axis.text.x=element_text(size=18), plot.title = element_text(hjust = 0.5)) +
  coord_cartesian(ylim = c(40, 100))

group_means = group_means %>% relocate('Temperature', .before = `Mean`)

# Not really needed
# group_means$Temperature[group_means$Temperature == 'High'] = 1
# group_means$Temperature[group_means$Temperature == 'Low'] = 0
# plot(group_means$Temperature, group_means$Mean)

kbl(group_means) %>%
 kable_classic(full_width = F)

```


```{r - generate CI and df tables for additive}
kbl(data) %>%
 kable_classic(full_width = F)

group_means=by(data$strength, data$additive, t.test)

group_means=matrix(c(unlist(group_means[['a']][5:4]),
                     unlist(group_means[['b']][5:4]),
                     unlist(group_means[['c']][5:4])),
                     nrow=3, ncol=3, byrow=T)

group_means
group_means = data.frame(cbind(group_means, c("a", "b", 'c')))

# convert to int

group_means$X1 = round(as.integer(group_means$X1), digit=2)
group_means$X2 = round(as.integer(group_means$X2), digit=2)
group_means$X3 = round(as.integer(group_means$X3), digit=2)

colnames(group_means)=c('Mean','Lower CI 95%','Upper CI 95%','Additive')

group_means

ggplot(group_means, aes(x=Additive, y=group_means[,1])) +
  geom_errorbar(aes(ymin=`Lower CI 95%`, ymax=`Upper CI 95%`), width=.1) +
  geom_line() + 
  geom_point() + 
  expand_limits(y=c(5, 20)) + 
  ylab("Carbon Fibire Strength") +
  xlab('Additive') + 
  labs(title="Average Carbon Fibire Strength with Additive type & 95% CIs") + 
  theme(text = element_text(size=13), axis.text.x=element_text(size=18), plot.title = element_text(hjust = 0.5)) +
  coord_cartesian(ylim = c(40, 100))

group_means = group_means %>% relocate('Additive', .before = `Mean`)

# Not really needed
# group_means$Temperature[group_means$Temperature == 'High'] = 1
# group_means$Temperature[group_means$Temperature == 'Low'] = 0
# plot(group_means$Temperature, group_means$Mean)

kbl(group_means) %>%
 kable_classic(full_width = F)

```


```{r - 2) create models (Submission deadline: 1.00pm 14th March 2022)}
"
Using an R programme, analyse these data considering the two predictors, i.e. time
(continuous) and day (categorical) and the response logcells. You should consider the
possibility of interactions between the predictors. Submit your complete R programme
code with suitable explanatory in-code comments.
"
data_v2 = subset(data, temperature=='High')


m1 = lm(strength ~ factor(temperature) + factor(additive) + factor(additive):factor(temperature), data = data)

# https://www.statology.org/diagnostic-plots-in-r/

# is there a difference in means?
anovatab(m1)
plot(m1)

# ggPredict(m1, interactive=TRUE)

# show with interval plot
# done
# compare the group means

drop1(m1,test='F')

# assess model
summary(m1)
vcov(m1)
confint(m1)

emmeans(m1, ~additive*temperature)

emmeans(m1, pairwise~additive)
emmeans(m1, pairwise~temperature)


lsmeans(m1, ~additive:temperature, adjust="fdr")

emmip(m1, additive ~ temperature) + theme(axis.text=element_text(size=14),
        axis.title=element_text(size=16, face="bold"))


glht_temperature = glht(m1, mcp("factor(temperature)" = "Tukey", interaction_average=TRUE))
summary(glht_temperature)

glht_additive = glht(m1, mcp("factor(additive)" = "Tukey", interaction_average=TRUE))
summary(glht_additive)


m1 %>% tbl_regression() # https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html


```


```{r - 3) Write report (Submission deadline: 1.00pm 14th March 2022)}
"
Report your fndings (4 pages maximum excluding R-code): summarise the relationship
between predictor(s) and the response


(what are the average effects, confdence intervals,
results of tests of hypotheses etc.). Present plots where appropriate.
"

confint(m1,level=0.95)
confint(m2,level=0.95)

anovatab(m1)
anovatab(m2)

# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/anova/how-to/one-way-anova/interpret-the-results/key-results/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/multiple-regression/before-you-start/overview/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/simple-regression/before-you-start/overview/
# https://support.minitab.com/en-us/minitab-express/1/help-and-how-to/modeling-statistics/regression/how-to/covariance/overview/


```