---
title: "C15311966_Maks_Drzezdzon"
output: html_notebook
---



```{r Setup }
needed_packages <- c("tidyverse")                      
# Extract not installed packages
not_installed <- needed_packages[!(needed_packages %in% installed.packages()[ , "Package"])]    
# Install not installed packages
if(length(not_installed)) install.packages(not_installed)

library(tidyverse)

df = read_csv("data-file.csv")
df = read_table("read-data.csv")

# ToDo's

# 1) Clean the Data Set
# 2) relevant summary statistics, single visualisation that 
# captures the relationship between at least 3 of the original variables
# 3) Focus on a subset of the data and create 3 derived variables 
# for the purposes of answering a single question of interest.


```


```{r Cleaning }
# 1) Clean the Data Set


```

```{r Analysis }
# 2) relevant summary statistics, single visualisation that 
# captures the relationship between at least 3 of the original variables


```

```{r Visualisation }
# 3) Focus on a subset of the data and create 3 derived variables 
# for the purposes of answering a single question of interest.

 
```