---
title: "C15311966 CA notebook"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
  output: html_notebook
---

## Setup
```{r}
library(tidyverse) # useful tooling
library(skimr) # for descriptions
library(ggplot2) # plots
library(pastecs) # for descriptive statistic summaries
library(psych) # useful descriptive functions
library(semTools) #For skewness and kurtosis
library(FSA) #For percentage
library(car) # For Levene's test for homogeneity of variance 
library(effectsize) #To calculate effect size for t-test

student_pref = read_csv("sperformance-dataset.csv")
getmode <- function(v) {
        uniqv <- unique(v)
        uniqv[which.max(tabulate(match(v, uniqv)))]
}
# Hypothesis Question: Does a student’s parents’ level of education influence their level of academic achievement?

```

## H0: There is no difference in students scores in regards to mothers education level.
## HA: There is a difference in students scores in regards to mothers education level.
### tlifesat Examine/Assess Normality
```{r assessing normality}
gg = ggplot(student_pref, aes(x=Medu))
gg = gg + geom_histogram(bins = 5, colour="cornflowerblue", aes(y=..density.., fill=..count..))
#adding a normal curve
#use stat_function to compute a normalised score for each value of tlifesat
#pass the mean and standard deviation
#use the na.rm parameter to say how missing values are handled
gg = gg + stat_function(fun=dnorm, color="red",args=list(mean=mean(student_pref$Medu, na.rm=TRUE), sd=sd(student_pref$Medu, na.rm=TRUE)))
#to display the graph 
gg

#Create a qqplot for mothers education levels
qqnorm(student_pref$Medu, main = "Mothers education levels")
qqline(student_pref$Medu, col = "blue", lwd = 2)

#stat.desc is a function from pastecs - make sure you include the basic switch=F to ensure you don't get scienfitic notation
pastecs::stat.desc(student_pref$Medu, basic=F)
dlife = pastecs::stat.desc(student_pref$Medu, basic=F)

#We can make our decision based on the value of the standardised score for skew and kurtosis
#We divide the skew statistic by the standard error to get the standardised score
#This will indicate if we have a problem
edu_skew = semTools::skew(student_pref$Medu)
edu_kurt = semTools::kurtosis(student_pref$Medu)
# skew falls slightly above +/-3 
edu_skew[1]/edu_skew[2]

# kurtosis falls inline with +/-10
edu_kurt[1]/edu_kurt[2]

#and by calculating the percentage of standardised scores for the variable itself that are outside our acceptable range
#This will tell us how big a problem we have
# Calculate the percentage of standardised scores that are greated than 1.96
# the perc function which is part of the FSA package which calculate the percentage that are within a range - you can look for greater than "gt", greater than or equal "geq", "gt", less than or equal "leq",  or less than "lt"),
# scale is a function that creates z scores, abs gets absolute value

mothers_education_level = abs(scale(student_pref$Medu))

FSA::perc(as.numeric(mothers_education_level), 1.96, "gt")
FSA::perc(as.numeric(mothers_education_level), 3.29, "gt")

```
```
Life Satisfaction can be considered to follow a normal distribution (m=`r round(mean(survey$tlifesat, na.rm=TRUE),2)`, sd=`r round(sd(survey$tlifesat, na.rm=TRUE),2)`, n=`r length(survey$tlifesat)-sum(is.na(survey$tlifesat))`, 100% of standardized scores falling within +/- 3.29). Therefore we can use a parametric difference test.
```


```{r descriptive statistics}


```