---
title: "Replace with Main Title"
author: "Your Name"
date: "AUTOMATIC"
---


```{r echo=FALSE, message=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r}
data(Adler, package="carData")
```

```{r}
with(Adler, Dotplot(rating, bin=FALSE))
```

```{r}
with(Adler, Hist(rating, scale="frequency", breaks="Sturges", 
  col="darkgray"))
```

```{r}
data()
```


```{r}
data()
```


```{r}
data(Salaries, package="carData")
```


```{r}
indexplot(Adler[,'rating', drop=FALSE], type='h', id.method='y', id.n=2)
```

```{r}
library(abind, pos=17)
```


```{r}
library(e1071, pos=18)
```


```{r}
numSummary(Adler[,"rating", drop=FALSE], statistics=c("mean", "sd", "IQR", 
  "quantiles"), quantiles=c(0,.25,.5,.75,1))
```

```{r}
data(Salaries, package="carData")
```

```{r}
numSummary(Salaries[,"salary", drop=FALSE], statistics=c("mean", "sd", 
  "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
```

```{r}
numSummary(Salaries[,"yrs.service", drop=FALSE], statistics=c("mean", "sd", 
  "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
```

```{r}
with(Salaries, Hist(salary, scale="frequency", breaks="Sturges", 
  col="darkgray"))
```

```{r}
with(Salaries, Hist(salary, groups=sex, scale="frequency", breaks="Sturges",
   col="darkgray"))
```

```{r}
local({
  .Table <- with(Salaries, table(discipline))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

```{r}
local({
  .Table <- xtabs(~discipline+sex, data=Salaries)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
densityPlot( ~ salary, data=Salaries, bw=bw.SJ, adjust=1, kernel=dnorm, 
  method="adaptive")
```

